/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class BManQuiz extends javax.swing.JFrame {

    /**
     * Creates new form AYM
     */
    public BManQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 1170));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setText("BATMAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 100, 130, 23);

        jButton2.setText("SUPERMAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 100, 123, 23);

        jButton3.setText("SPIDERMAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 100, 134, 23);

        jButton4.setText("IRONMAN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(180, 230, 123, 23);

        jButton5.setText("HULK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(460, 220, 134, 23);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 0));
        jTextField1.setForeground(new java.awt.Color(0, 0, 204));
        jTextField1.setText("Which Superhero is Nicknamed the Caped Crusader");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 20, 316, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 0, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9f9c8b11594634046fc553498707863e[1].jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 750, 690);

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(60, 370, 59, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static int op;
    static String yaya;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        op = 0;
        jTextField2.setText("" + 0);
        yaya = jTextField2.getText();
        JOptionPane.showMessageDialog(null, "wrong");
        this.setVisible(false);
        StorePage obj = new StorePage();
        new StorePage().setVisible(true);
        jButton2.setIcon(new ImageIcon("C:\\Users\\Admin\\Desktop\\bm.jpg"));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        op = 25;
        jTextField2.setText("" + 20);
        yaya = jTextField2.getText();
        JOptionPane.showMessageDialog(null, "Correct");
        System.out.print(MagicSquare.yui);
        this.setVisible(false);
        StorePage obj = new StorePage();
        new StorePage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        op = 0;
        JOptionPane.showMessageDialog(null, "wrong");
        this.setVisible(false);
        jTextField2.setText("" + 0);
        yaya = jTextField2.getText();
        StorePage obj = new StorePage();
        new StorePage().setVisible(true);
        jButton3.setIcon(new ImageIcon("C:\\Users\\Admin\\Desktop\\ca.jpg"));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        op = 0;
        JOptionPane.showMessageDialog(null, "wrong");
        this.setVisible(false);
        jTextField2.setText("" + 0);
        yaya = jTextField2.getText();
        StorePage obj = new StorePage();
        new StorePage().setVisible(true);
        jButton4.setIcon(new ImageIcon("C:\\Users\\Admin\\Desktop\\sm.jpg"));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        op = 0;
        JOptionPane.showMessageDialog(null, "wrong");
        this.setVisible(false);
        jTextField2.setText("" + 0);
        yaya = jTextField2.getText();
        new StorePage().setVisible(true);
        jButton5.setIcon(new ImageIcon("C:\\Users\\Admin\\Desktop\\spidey.jpg"));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTextField2.setVisible(false);
        jButton2.setIcon(new ImageIcon("C:\\Users\\Admin\\Desktop\\bm.jpg"));
        jButton1.setIcon(new ImageIcon("C:\\Users\\Admin\\Desktop\\im.jpg"));
        jButton3.setIcon(new ImageIcon("C:\\Users\\Admin\\Desktop\\ca.jpg"));
        jButton4.setIcon(new ImageIcon("C:\\Users\\Admin\\Desktop\\sm.jpg"));
        jButton5.setIcon(new ImageIcon("C:\\Users\\Admin\\Desktop\\spidey.jpg"));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BManQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BManQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BManQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BManQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BManQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
