
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Raghav
 */
public class MagicSquare extends javax.swing.JFrame {

    /**
     * Creates new form magicsquare
     */
    public MagicSquare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 0, 153));
        jTextField1.setForeground(new java.awt.Color(204, 255, 255));
        jTextField1.setText("4");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(37, 73, 46, 30);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(153, 0, 153));
        jTextField2.setForeground(new java.awt.Color(153, 255, 255));
        jTextField2.setText("9");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(113, 73, 46, 30);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(153, 0, 153));
        jTextField3.setForeground(new java.awt.Color(153, 255, 255));
        jTextField3.setText("2");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(188, 73, 46, 30);

        jTextField4.setBackground(new java.awt.Color(153, 255, 153));
        jTextField4.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField4);
        jTextField4.setBounds(37, 134, 46, 30);

        jTextField5.setBackground(new java.awt.Color(153, 255, 153));
        jTextField5.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField5);
        jTextField5.setBounds(37, 196, 46, 30);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(153, 0, 153));
        jTextField6.setForeground(new java.awt.Color(153, 255, 255));
        jTextField6.setText("5");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(113, 134, 46, 30);

        jTextField7.setBackground(new java.awt.Color(153, 255, 153));
        jTextField7.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField7);
        jTextField7.setBounds(188, 134, 46, 30);

        jTextField8.setBackground(new java.awt.Color(153, 255, 153));
        jTextField8.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField8);
        jTextField8.setBounds(113, 196, 46, 30);

        jTextField9.setBackground(new java.awt.Color(153, 255, 153));
        jTextField9.setForeground(new java.awt.Color(255, 51, 0));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(188, 196, 46, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(282, 252, 100, 40);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(364, 153, 6, 20);

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 255, 0));
        jTextField11.setForeground(new java.awt.Color(51, 51, 255));
        jTextField11.setText("COMPLETE THE MAGIC SQUARE");
        getContentPane().add(jTextField11);
        jTextField11.setBounds(82, 23, 225, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Jokerlaughs[1].jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
    }//GEN-LAST:event_jTextField9ActionPerformed
    static int yui;
    static String tot;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a = Integer.parseInt(jTextField4.getText());
        int b = Integer.parseInt(jTextField7.getText());
        int c = Integer.parseInt(jTextField5.getText());
        int d = Integer.parseInt(jTextField8.getText());
        int e = Integer.parseInt(jTextField9.getText());
        if (a == 3 && b == 7 && c == 8 && d == 1 && e == 6) {
            JOptionPane.showMessageDialog(null, "Correct");
            yui = 20;
            jTextField10.setText("" + 20);
        } else {
            yui = 0;
            JOptionPane.showMessageDialog(null, "Wrong");
            jTextField10.setText("" + 0);
        }
        tot = jTextField10.getText();
        this.setVisible(false);
        BManQuiz obj = new BManQuiz();
        new BManQuiz().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTextField10.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagicSquare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagicSquare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagicSquare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagicSquare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagicSquare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
