
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author admin
 */
public class RockPaperScissorsLizardSpock extends javax.swing.JFrame {

    /**
     * Creates new form RockPaperScissorsLizardSpock
     */
    public RockPaperScissorsLizardSpock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setText("Rock, Paper, Scissors, Lizard, Spock");

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        l2.setFont(new java.awt.Font("Magneto", 0, 14)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        l3.setFont(new java.awt.Font("Magneto", 0, 14)); // NOI18N
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Magneto", 0, 14)); // NOI18N
        jLabel2.setText("Choose Rock, Paper, Scissors, Lizard or Spock ");

        jList1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Rock", "Paper", "Scissors", "Lizard", "Spock" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jList1FocusGained(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jButton2.setText("Go Back Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(224, 224, 224))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s = (String) jList1.getSelectedValue();
        int j = 0;
        if (s.equals("Rock")) {
            j = 0;
        } else if (s.equals("Paper")) {
            j = 1;
        } else if (s.equals("Scissors")) {
            j = 2;
        } else if (s.equals("Lizard")) {
            j = 3;
        } else if (s.equals("Spock")) {
            j = 4;
        }
        int i = j;
        int cv = new java.util.Random().nextInt(4);

        System.out.print(cv);
        if (i == cv) {
            l2.setText("OOPS!! Computer chose the same option!!! Try Again!!!");
        } else if (((i == 0) && (cv == 2)) || ((i == 0) && (cv == 3)) || ((i == 1) && (cv == 0)) || ((i == 1) && (cv == 4)) || ((i == 2) && (cv == 3)) || ((i == 2) && (cv == 1)) || ((i == 3) && (cv == 1)) || ((i == 3) && (cv == 4)) || ((i == 4) && (cv == 0)) || ((i == 4) && (cv == 2))) {
            l2.setText("Congrats, you win!!!");
        } else if (((i == 0) && (cv == 1)) || ((i == 0) && (cv == 4)) || ((i == 1) && (cv == 3)) || ((i == 1) && (cv == 2)) || ((i == 2) && (cv == 4)) || ((i == 2) && (cv == 0)) || ((i == 3) && (cv == 0)) || ((i == 3) && (cv == 2)) || ((i == 4) && (cv == 3)) || ((i == 4) && (cv == 1))) {
            l2.setText("Oh no!!! You Lose!");
        }
        if (cv == 0) {
            l3.setText("Computer Chose Rock!");
        }
        if (cv == 1) {
            l3.setText("Computer Chose Paper!");
        }
        if (cv == 2) {
            l3.setText("Computer Chose Scissors!");
        }
        if (cv == 3) {
            l3.setText("Computer Chose Lizard!");
        }
        if (cv == 4) {
            l3.setText("Computer Chose Spock!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GameSelectForm obj = new GameSelectForm();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        String s = (String) jList1.getSelectedValue();
        int j = 0;
        if (s.equals("Rock")) {
            j = 0;
        } else if (s.equals("Paper")) {
            j = 1;
        } else if (s.equals("Scissors")) {
            j = 2;
        } else if (s.equals("Lizard")) {
            j = 3;
        } else if (s.equals("Spock")) {
            j = 4;
        }
        int i = j;
        int cv = new java.util.Random().nextInt(4);

        System.out.print(cv);
        if (i == cv) {
            l2.setText("OOPS!! Computer chose the same option!!! Try Again!!!");
        } else if (((i == 0) && (cv == 2)) || ((i == 0) && (cv == 3)) || ((i == 1) && (cv == 0)) || ((i == 1) && (cv == 4)) || ((i == 2) && (cv == 3)) || ((i == 2) && (cv == 1)) || ((i == 3) && (cv == 1)) || ((i == 3) && (cv == 4)) || ((i == 4) && (cv == 0)) || ((i == 4) && (cv == 2))) {
            l2.setText("Congrats, you win!!!");
        } else if (((i == 0) && (cv == 1)) || ((i == 0) && (cv == 4)) || ((i == 1) && (cv == 3)) || ((i == 1) && (cv == 2)) || ((i == 2) && (cv == 4)) || ((i == 2) && (cv == 0)) || ((i == 3) && (cv == 0)) || ((i == 3) && (cv == 2)) || ((i == 4) && (cv == 3)) || ((i == 4) && (cv == 1))) {
            l2.setText("Oh no!!! You Lose!");
        }
        if (cv == 0) {
            l3.setText("Computer Chose Rock!");
        }
        if (cv == 1) {
            l3.setText("Computer Chose Paper!");
        }
        if (cv == 2) {
            l3.setText("Computer Chose Scissors!");
        }
        if (cv == 3) {
            l3.setText("Computer Chose Lizard!");
        }
        if (cv == 4) {
            l3.setText("Computer Chose Spock!");
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained
    }//GEN-LAST:event_jList1FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsLizardSpock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsLizardSpock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsLizardSpock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsLizardSpock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RockPaperScissorsLizardSpock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    // End of variables declaration//GEN-END:variables
}
