/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class StorePage extends javax.swing.JFrame {

    /**
     * Creates new form ENPT
     */
    public StorePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1600, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesWFMLS8GR.jpg"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 130, 140, 40);

        jButton2.setBackground(new java.awt.Color(51, 0, 204));
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/$_35[1].jpg"))); // NOI18N
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 210, 140, 50);

        jButton3.setBackground(new java.awt.Color(0, 153, 0));
        jButton3.setForeground(new java.awt.Color(0, 153, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/41vWA7CNPtL._SY300_[1].jpg"))); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(50, 330, 140, 40);

        jLabel1.setText("100 INR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 230, 73, 24);

        jLabel2.setText("200 INR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 140, 50, 24);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(833, 99, 0, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(759, 487, 0, 20);

        jButton4.setText("ADD TO CART");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(515, 130, 130, 23);

        jButton5.setText("CANCEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(670, 130, 100, 23);

        jButton6.setText("ADD TO CART");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(520, 240, 130, 23);

        jButton7.setText("CANCEL");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(670, 240, 100, 23);

        jButton8.setText("ADD TO CART");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(520, 330, 130, 23);

        jButton9.setText("CANCEL");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(670, 330, 100, 23);

        jButton10.setText("GO TO PAYMENT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(330, 540, 130, 30);

        t1.setEditable(false);
        t1.setColumns(20);
        t1.setRows(5);
        jScrollPane1.setViewportView(t1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(46, 470, 250, 130);

        jTextField1.setEditable(false);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(310, 470, 150, 40);

        jLabel4.setText("100 INR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 340, 61, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(136, 1159, 6, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(198, 1159, 6, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(671, 1147, 6, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(647, 353, 0, 20);

        jButton11.setText("jButton11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(620, 913, 57, 23);

        jTextField5.setText("jTextField5");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(306, 1178, 0, 20);

        jTextField6.setText("jTextField6");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(152, 1159, 9, 20);

        jTextField7.setText("jTextField7");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(179, 1159, 9, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("1");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(290, 130, 31, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(340, 130, 43, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("3");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(414, 130, 43, 23);

        buttonGroup2.add(r1);
        r1.setText("1");
        getContentPane().add(r1);
        r1.setBounds(290, 240, 31, 23);

        buttonGroup3.add(r5);
        r5.setText("2");
        getContentPane().add(r5);
        r5.setBounds(350, 340, 35, 23);

        buttonGroup2.add(r3);
        r3.setText("3");
        getContentPane().add(r3);
        r3.setBounds(410, 240, 43, 23);

        buttonGroup3.add(r4);
        r4.setText("1");
        getContentPane().add(r4);
        r4.setBounds(290, 340, 31, 23);

        buttonGroup2.add(r2);
        r2.setText("2");
        getContentPane().add(r2);
        r2.setBounds(340, 240, 40, 23);

        buttonGroup3.add(r6);
        r6.setText("3");
        getContentPane().add(r6);
        r6.setBounds(420, 340, 43, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Batman-Arkham-Origins-Wallpaper-Full-Hd[1].jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 20, 1270, 950);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int a, b, c, kb, k = 0;
    static int p = 0;
    static String ss, sr, ab, bc, bd;
    static int pore, pore1, pore2;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jRadioButton1.isSelected() == true) {
            k += 200;
            t1.append("\nBatman T-Shirt");
            jRadioButton2.setVisible(false);
            jRadioButton3.setVisible(false);
        } else if (jRadioButton2.isSelected() == true) {
            k += 400;
            t1.append("\nBatman T-Shirt x 2");
            jRadioButton1.setVisible(false);
            jRadioButton3.setVisible(false);
        } else if (jRadioButton3.isSelected() == true) {
            k += 600;
            t1.append("\nBatman T-Shirt x 3");
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
        } else {
            k += 0;
        }
        jButton4.setVisible(false);
        jTextField1.setText("" + k);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jRadioButton2.setVisible(true);
        jRadioButton1.setVisible(true);
        jRadioButton3.setVisible(true);
        jButton4.setVisible(true);
        t1.setText("");
        jTextField1.setText("");
        k = 0;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (r1.isSelected() == true) {
            k += 100;
            t1.append("\nBatman Key chain");
            r2.setVisible(false);
            r3.setVisible(false);
        } else if (r2.isSelected() == true) {
            k += 200;
            t1.append("\nBatman Key chain x 2");
            r1.setVisible(false);
            r3.setVisible(false);
        } else if (r3.isSelected() == true) {
            k += 300;
            t1.append("\nBatman Key chain x 3");
            r1.setVisible(false);
            r2.setVisible(false);
        } else {
            k += 0;
        }
        jButton6.setVisible(false);
        jTextField1.setText("" + k);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        r2.setVisible(true);
        r1.setVisible(true);
        r3.setVisible(true);
        jButton6.setVisible(true);
        t1.setText("");
        k = 0;
        jTextField1.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (r4.isSelected() == true) {
            k += 100;
            t1.append("\nBatman Action Figure");
            r5.setVisible(false);
            r6.setVisible(false);
        } else if (r5.isSelected() == true) {
            k += 200;
            t1.append("\nBatman Action Figure x 2");
            r4.setVisible(false);
            r6.setVisible(false);
        } else if (r6.isSelected() == true) {
            k += 300;
            t1.append("\nBatman Action Figure x 3");
            r4.setVisible(false);
            r5.setVisible(false);
        } else {
            k += 0;
        }
        jButton8.setVisible(false);
        jTextField1.setText("" + k);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        r4.setVisible(true);
        r5.setVisible(true);
        r6.setVisible(true);
        jButton8.setVisible(true);
        t1.setText("");
        k = 0;
        jTextField1.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTextField4.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jComboBox3.setVisible(false);
        jButton11.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jTextField5.setText("" + (jComboBox1.getSelectedIndex()));
        ab = jTextField5.getText();
        jTextField6.setText("" + (jComboBox2.getSelectedIndex()));
        bc = jTextField6.getText();
        jTextField7.setText("" + (jComboBox3.getSelectedIndex()));
        bd = jTextField7.getText();
        kb = jComboBox1.getSelectedIndex();
        if (jRadioButton1.isSelected() == true) {
            pore = 2;
        } else if (jRadioButton2.isSelected() == true) {
            pore = 1;
        } else if (jRadioButton3.isSelected() == true) {
            pore = 0;
        } else if (jRadioButton1.isSelected() == false || jRadioButton2.isSelected() == false || jRadioButton3.isSelected() == false) {
            pore = 3;
        }
        if (r1.isSelected() == true) {
            pore1 = 2;
        } else if (r2.isSelected() == true) {
            pore1 = 1;
        } else if (r3.isSelected() == true) {
            pore1 = 0;
        } else if (r1.isSelected() == false || r2.isSelected() == false || r3.isSelected() == false) {
            pore1 = 3;
        }

        if (r4.isSelected() == true) {
            pore2 = 2;
        } else if (r5.isSelected() == true) {
            pore2 = 1;
        } else if (r6.isSelected() == true) {
            pore2 = 0;
        } else if (r4.isSelected() == false || r5.isSelected() == false || r6.isSelected() == false) {
            pore2 = 3;
        }
        ss = t1.getText();
        sr = jTextField1.getText();

        this.setVisible(false);
        new CheckoutPage().setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jTextField5.setText("" + (jComboBox1.getSelectedIndex() + 1));
        System.out.print(ab);
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StorePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private static javax.swing.JTextArea t1;
    // End of variables declaration//GEN-END:variables
}
